FFmpeg: doc/examples/avio_dir_cmd.c File Reference
avio_dir_cmd.c File Reference
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavformat/avio.h>
Functions
static const char * type_string (int type)
static int list_op (const char *input_dir)
static int del_op (const char *url)
static int move_op (const char *src, const char *dst)
static void usage (const char *program_name)
int main (int argc, char *argv[])
Function Documentation
type_string()
static const char* type_string (int type) static
Definition at line 27 of file avio_dir_cmd.c.
Referenced by list_op().
list_op()
static int list_op (const char * input_dir) static
Definition at line 57 of file avio_dir_cmd.c.
Referenced by main().
del_op()
static int del_op (const char * url) static
Definition at line 105 of file avio_dir_cmd.c.
Referenced by main().
move_op()
static int move_op (const char * src, const char * dst) static
Definition at line 113 of file avio_dir_cmd.c.
Referenced by main().
usage()
static void usage (const char * program_name) static
Examples:
ffhash.c.
Definition at line 122 of file avio_dir_cmd.c.
Referenced by main().
main()
int main (int argc, char * argv[])
Examples:
ffhash.c.
Definition at line 134 of file avio_dir_cmd.c.