FFmpeg: doc/examples/encode_audio.c File Reference
encode_audio.c File Reference
audio encoding with libavcodec API example.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <libavcodec/avcodec.h>
#include <libavutil/channel_layout.h>
#include <libavutil/common.h>
#include <libavutil/frame.h>
#include <libavutil/samplefmt.h>
Functions
static int check_sample_fmt (const AVCodec *codec, enum AVSampleFormat sample_fmt)
static int select_sample_rate (const AVCodec *codec)
static int select_channel_layout (const AVCodec *codec)
static void encode (AVCodecContext *ctx, AVFrame *frame, AVPacket *pkt, FILE *output)
int main (int argc, char **argv)
Detailed Description
audio encoding with libavcodec API example.
Definition in file encode_audio.c.
Function Documentation
check_sample_fmt()
static int check_sample_fmt (const AVCodec * codec, enum AVSampleFormat sample_fmt) static
Examples:
encode_audio.c.
Definition at line 42 of file encode_audio.c.
Referenced by main().
select_sample_rate()
static int select_sample_rate (const AVCodec * codec) static
Examples:
encode_audio.c.
Definition at line 55 of file encode_audio.c.
Referenced by main().
select_channel_layout()
static int select_channel_layout (const AVCodec * codec) static
Examples:
encode_audio.c.
Definition at line 73 of file encode_audio.c.
Referenced by main().
encode()
static void encode (AVCodecContext * ctx, AVFrame * frame, AVPacket * pkt, FILE * output) static
Examples:
encode_audio.c.
Definition at line 95 of file encode_audio.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Examples:
encode_audio.c.
Definition at line 123 of file encode_audio.c.