FFmpeg: AVFrame
AVFrame
libavutil » Data Structures
AVFrame is an abstraction for reference-counted raw multimedia data.
Modules
AV_FRAME_FLAGS
Flags describing additional frame properties.
Files
file frame.h
reference-counted frame API
Data Structures
struct AVFrameSideData
Structure to hold side data for an AVFrame.
struct AVFrame
This structure describes decoded (raw) audio or video data.
Enumerations
enum AVFrameSideDataType {
AV_FRAME_DATA_PANSCAN, AV_FRAME_DATA_A53_CC, AV_FRAME_DATA_STEREO3D, AV_FRAME_DATA_MATRIXENCODING,
AV_FRAME_DATA_DOWNMIX_INFO, AV_FRAME_DATA_REPLAYGAIN, AV_FRAME_DATA_DISPLAYMATRIX, AV_FRAME_DATA_AFD,
AV_FRAME_DATA_MOTION_VECTORS, AV_FRAME_DATA_SKIP_SAMPLES, AV_FRAME_DATA_AUDIO_SERVICE_TYPE, AV_FRAME_DATA_MASTERING_DISPLAY_METADATA,
AV_FRAME_DATA_GOP_TIMECODE, AV_FRAME_DATA_SPHERICAL, AV_FRAME_DATA_CONTENT_LIGHT_LEVEL, AV_FRAME_DATA_ICC_PROFILE
}
enum AVActiveFormatDescription {
AV_AFD_SAME = 8, AV_AFD_4_3 = 9, AV_AFD_16_9 = 10, AV_AFD_14_9 = 11,
AV_AFD_4_3_SP_14_9 = 13, AV_AFD_16_9_SP_14_9 = 14, AV_AFD_SP_4_3 = 15
}
enum { AV_FRAME_CROP_UNALIGNED = 1 << 0 }
Flags for frame cropping.
Functions
attribute_deprecated int64_t av_frame_get_best_effort_timestamp (const AVFrame *frame)
Accessors for some AVFrame fields.
attribute_deprecated void av_frame_set_best_effort_timestamp (AVFrame *frame, int64_t val)
attribute_deprecated int64_t av_frame_get_pkt_duration (const AVFrame *frame)
attribute_deprecated void av_frame_set_pkt_duration (AVFrame *frame, int64_t val)
attribute_deprecated int64_t av_frame_get_pkt_pos (const AVFrame *frame)
attribute_deprecated void av_frame_set_pkt_pos (AVFrame *frame, int64_t val)
attribute_deprecated int64_t av_frame_get_channel_layout (const AVFrame *frame)
attribute_deprecated void av_frame_set_channel_layout (AVFrame *frame, int64_t val)
attribute_deprecated int av_frame_get_channels (const AVFrame *frame)
attribute_deprecated void av_frame_set_channels (AVFrame *frame, int val)
attribute_deprecated int av_frame_get_sample_rate (const AVFrame *frame)
attribute_deprecated void av_frame_set_sample_rate (AVFrame *frame, int val)
attribute_deprecated AVDictionary * av_frame_get_metadata (const AVFrame *frame)
attribute_deprecated void av_frame_set_metadata (AVFrame *frame, AVDictionary *val)
attribute_deprecated int av_frame_get_decode_error_flags (const AVFrame *frame)
attribute_deprecated void av_frame_set_decode_error_flags (AVFrame *frame, int val)
attribute_deprecated int av_frame_get_pkt_size (const AVFrame *frame)
attribute_deprecated void av_frame_set_pkt_size (AVFrame *frame, int val)
attribute_deprecated int8_t * av_frame_get_qp_table (AVFrame *f, int *stride, int *type)
attribute_deprecated int av_frame_set_qp_table (AVFrame *f, AVBufferRef *buf, int stride, int type)
attribute_deprecated enum AVColorSpace av_frame_get_colorspace (const AVFrame *frame)
attribute_deprecated void av_frame_set_colorspace (AVFrame *frame, enum AVColorSpace val)
attribute_deprecated enum AVColorRange av_frame_get_color_range (const AVFrame *frame)
attribute_deprecated void av_frame_set_color_range (AVFrame *frame, enum AVColorRange val)
const char * av_get_colorspace_name (enum AVColorSpace val)
Get the name of a colorspace.
AVFrame * av_frame_alloc (void)
Allocate an AVFrame and set its fields to default values.
void av_frame_free (AVFrame **frame)
Free the frame and any dynamically allocated objects in it, e.g.
int av_frame_ref (AVFrame *dst, const AVFrame *src)
Set up a new reference to the data described by the source frame.
AVFrame * av_frame_clone (const AVFrame *src)
Create a new frame that references the same data as src.
void av_frame_unref (AVFrame *frame)
Unreference all the buffers referenced by frame and reset the frame fields.
void av_frame_move_ref (AVFrame *dst, AVFrame *src)
Move everything contained in src to dst and reset src.
int av_frame_get_buffer (AVFrame *frame, int align)
Allocate new buffer(s) for audio or video data.
int av_frame_is_writable (AVFrame *frame)
Check if the frame data is writable.
int av_frame_make_writable (AVFrame *frame)
Ensure that the frame data is writable, avoiding data copy if possible.
int av_frame_copy (AVFrame *dst, const AVFrame *src)
Copy the frame data from src to dst.
int av_frame_copy_props (AVFrame *dst, const AVFrame *src)
Copy only "metadata" fields from src to dst.
AVBufferRef * av_frame_get_plane_buffer (AVFrame *frame, int plane)
Get the buffer reference a given data plane is stored in.
AVFrameSideData * av_frame_new_side_data (AVFrame *frame, enum AVFrameSideDataType type, int size)
Add a new side data to a frame.
AVFrameSideData * av_frame_get_side_data (const AVFrame *frame, enum AVFrameSideDataType type)
void av_frame_remove_side_data (AVFrame *frame, enum AVFrameSideDataType type)
If side data of the supplied type exists in the frame, free it and remove it from the frame.
int av_frame_apply_cropping (AVFrame *frame, int flags)
Crop the given video AVFrame according to its crop_left/crop_top/crop_right/ crop_bottom fields.
const char * av_frame_side_data_name (enum AVFrameSideDataType type)
Detailed Description
AVFrame is an abstraction for reference-counted raw multimedia data.
Enumeration Type Documentation
AVFrameSideDataType
enum AVFrameSideDataType
Enumerator
AV_FRAME_DATA_PANSCAN
The data is the AVPanScan struct defined in libavcodec.
AV_FRAME_DATA_A53_CC
ATSC A53 Part 4 Closed Captions.
A53 CC bitstream is stored as uint8_t in AVFrameSideData.data. The number of bytes of CC data is AVFrameSideData.size.
AV_FRAME_DATA_STEREO3D
Stereoscopic 3d metadata.
The data is the AVStereo3D struct defined in libavutil/stereo3d.h.
AV_FRAME_DATA_MATRIXENCODING
The data is the AVMatrixEncoding enum defined in libavutil/channel_layout.h.
AV_FRAME_DATA_DOWNMIX_INFO
Metadata relevant to a downmix procedure.
The data is the AVDownmixInfo struct defined in libavutil/downmix_info.h.
AV_FRAME_DATA_REPLAYGAIN
ReplayGain information in the form of the AVReplayGain struct.
AV_FRAME_DATA_DISPLAYMATRIX
This side data contains a 3x3 transformation matrix describing an affine transformation that needs to be applied to the frame for correct presentation.
See libavutil/display.h for a detailed description of the data.
AV_FRAME_DATA_AFD
Active Format Description data consisting of a single byte as specified in ETSI TS 101 154 using AVActiveFormatDescription enum.
AV_FRAME_DATA_MOTION_VECTORS
Motion vectors exported by some codecs (on demand through the export_mvs flag set in the libavcodec AVCodecContext flags2 option).
The data is the AVMotionVector struct defined in libavutil/motion_vector.h.
AV_FRAME_DATA_SKIP_SAMPLES
Recommmends skipping the specified number of samples.
This is exported only if the "skip_manual" AVOption is set in libavcodec. This has the same format as AV_PKT_DATA_SKIP_SAMPLES.
u32le number of samples to skip from start of this packet
u32le number of samples to skip from end of this packet
u8    reason for start skip
u8    reason for end   skip (0=padding silence, 1=convergence)
AV_FRAME_DATA_AUDIO_SERVICE_TYPE
This side data must be associated with an audio frame and corresponds to enum AVAudioServiceType defined in avcodec.h.
AV_FRAME_DATA_MASTERING_DISPLAY_METADATA
Mastering display metadata associated with a video frame.
The payload is an AVMasteringDisplayMetadata type and contains information about the mastering display color volume.
AV_FRAME_DATA_GOP_TIMECODE
The GOP timecode in 25 bit timecode format.
Data format is 64-bit integer. This is set on the first frame of a GOP that has a temporal reference of 0.
AV_FRAME_DATA_SPHERICAL
The data represents the AVSphericalMapping structure defined in libavutil/spherical.h.
AV_FRAME_DATA_CONTENT_LIGHT_LEVEL
Content light level (based on CTA-861.3).
This payload contains data in the form of the AVContentLightMetadata struct.
AV_FRAME_DATA_ICC_PROFILE
The data contains an ICC profile as an opaque octet buffer following the format described by ISO 15076-1 with an optional name defined in the metadata key entry "name".
Definition at line 48 of file frame.h.
AVActiveFormatDescription
enum AVActiveFormatDescription
Enumerator
AV_AFD_SAME
AV_AFD_4_3
AV_AFD_16_9
AV_AFD_14_9
AV_AFD_4_3_SP_14_9
AV_AFD_16_9_SP_14_9
AV_AFD_SP_4_3
Definition at line 146 of file frame.h.
anonymous enum
anonymous enum
Flags for frame cropping.
Enumerator
AV_FRAME_CROP_UNALIGNED
Apply the maximum possible cropping, even if it requires setting the AVFrame.data[] entries to unaligned pointers.
Passing unaligned data to FFmpeg API is generally not allowed, and causes undefined behavior (such as crashes). You can pass unaligned data only to FFmpeg APIs that are explicitly documented to accept it. Use this flag only if you absolutely know what you are doing.
Definition at line 820 of file frame.h.
Function Documentation
av_frame_get_best_effort_timestamp()
attribute_deprecated int64_t av_frame_get_best_effort_timestamp (const AVFrame * frame)
Accessors for some AVFrame fields.
These used to be provided for ABI compatibility, and do not need to be used anymore.
av_frame_set_best_effort_timestamp()
attribute_deprecated void av_frame_set_best_effort_timestamp (AVFrame * frame, int64_t val)
av_frame_get_pkt_duration()
attribute_deprecated int64_t av_frame_get_pkt_duration (const AVFrame * frame)
av_frame_set_pkt_duration()
attribute_deprecated void av_frame_set_pkt_duration (AVFrame * frame, int64_t val)
av_frame_get_pkt_pos()
attribute_deprecated int64_t av_frame_get_pkt_pos (const AVFrame * frame)
av_frame_set_pkt_pos()
attribute_deprecated void av_frame_set_pkt_pos (AVFrame * frame, int64_t val)
av_frame_get_channel_layout()
attribute_deprecated int64_t av_frame_get_channel_layout (const AVFrame * frame)
av_frame_set_channel_layout()
attribute_deprecated void av_frame_set_channel_layout (AVFrame * frame, int64_t val)
av_frame_get_channels()
attribute_deprecated int av_frame_get_channels (const AVFrame * frame)
av_frame_set_channels()
attribute_deprecated void av_frame_set_channels (AVFrame * frame, int val)
av_frame_get_sample_rate()
attribute_deprecated int av_frame_get_sample_rate (const AVFrame * frame)
av_frame_set_sample_rate()
attribute_deprecated void av_frame_set_sample_rate (AVFrame * frame, int val)
av_frame_get_metadata()
attribute_deprecated AVDictionary* av_frame_get_metadata (const AVFrame * frame)
av_frame_set_metadata()
attribute_deprecated void av_frame_set_metadata (AVFrame * frame, AVDictionary * val)
av_frame_get_decode_error_flags()
attribute_deprecated int av_frame_get_decode_error_flags (const AVFrame * frame)
av_frame_set_decode_error_flags()
attribute_deprecated void av_frame_set_decode_error_flags (AVFrame * frame, int val)
av_frame_get_pkt_size()
attribute_deprecated int av_frame_get_pkt_size (const AVFrame * frame)
av_frame_set_pkt_size()
attribute_deprecated void av_frame_set_pkt_size (AVFrame * frame, int val)
av_frame_get_qp_table()
attribute_deprecated int8_t* av_frame_get_qp_table (AVFrame * f, int * stride, int * type)
av_frame_set_qp_table()
attribute_deprecated int av_frame_set_qp_table (AVFrame * f, AVBufferRef * buf, int stride, int type)
av_frame_get_colorspace()
attribute_deprecated enum AVColorSpace av_frame_get_colorspace (const AVFrame * frame)
av_frame_set_colorspace()
attribute_deprecated void av_frame_set_colorspace (AVFrame * frame, enum AVColorSpace val)
av_frame_get_color_range()
attribute_deprecated enum AVColorRange av_frame_get_color_range (const AVFrame * frame)
av_frame_set_color_range()
attribute_deprecated void av_frame_set_color_range (AVFrame * frame, enum AVColorRange val)
av_get_colorspace_name()
const char* av_get_colorspace_name (enum AVColorSpace val)
Get the name of a colorspace.
Returns
a static string identifying the colorspace; can be NULL.
av_frame_alloc()
AVFrame* av_frame_alloc (void)
Allocate an AVFrame and set its fields to default values.
The resulting struct must be freed using av_frame_free().
Returns
An AVFrame filled with default values or NULL on failure.
Note
this only allocates the AVFrame itself, not the data buffers. Those must be allocated through other means, e.g. with av_frame_get_buffer() or manually.
Examples:
decode_audio.c, decode_video.c, demuxing_decoding.c, encode_audio.c, encode_video.c, filter_audio.c, filtering_audio.c, filtering_video.c, hw_decode.c, muxing.c, transcode_aac.c, transcoding.c, and vaapi_encode.c.
Referenced by alloc_audio_frame(), alloc_picture(), decode_write(), filter_encode_write_frame(), init_input_frame(), init_output_frame(), and main().
av_frame_free()
void av_frame_free (AVFrame ** frame)
Free the frame and any dynamically allocated objects in it, e.g.
extended_data. If the frame is reference counted, it will be unreferenced first.
Parameters
frame frame to be freed. The pointer will be set to NULL.
Examples:
decode_audio.c, decode_video.c, demuxing_decoding.c, encode_audio.c, encode_video.c, filter_audio.c, filtering_audio.c, filtering_video.c, hw_decode.c, muxing.c, transcode_aac.c, transcoding.c, and vaapi_encode.c.
Referenced by close_stream(), decode_write(), encode_write_frame(), filter_encode_write_frame(), init_output_frame(), load_encode_and_write(), main(), and read_decode_convert_and_store().
av_frame_ref()
int av_frame_ref (AVFrame * dst, const AVFrame * src)
Set up a new reference to the data described by the source frame.
Copy frame properties from src to dst and create a new reference for each AVBufferRef from src.
If src is not reference counted, new buffers are allocated and the data is copied.
Warning
: dst MUST have been either unreferenced with av_frame_unref(dst), or newly allocated with av_frame_alloc() before calling this function, or undefined behavior will occur.
Returns
0 on success, a negative AVERROR on error
av_frame_clone()
AVFrame* av_frame_clone (const AVFrame * src)
Create a new frame that references the same data as src.
This is a shortcut for av_frame_alloc()+av_frame_ref().
Returns
newly created AVFrame on success, NULL on error.
av_frame_unref()
void av_frame_unref (AVFrame * frame)
Unreference all the buffers referenced by frame and reset the frame fields.
Examples:
demuxing_decoding.c, filter_audio.c, filtering_audio.c, and filtering_video.c.
Referenced by decode_packet(), and main().
av_frame_move_ref()
void av_frame_move_ref (AVFrame * dst, AVFrame * src)
Move everything contained in src to dst and reset src.
Warning
: dst is not unreferenced, but directly overwritten without reading or deallocating its contents. Call av_frame_unref(dst) manually before calling this function to ensure that no memory is leaked.
av_frame_get_buffer()
int av_frame_get_buffer (AVFrame * frame, int align)
Allocate new buffer(s) for audio or video data.
The following fields must be set on frame before calling this function:
format (pixel format for video, sample format for audio)
width and height for video
nb_samples and channel_layout for audio
This function will fill AVFrame.data and AVFrame.buf arrays and, if necessary, allocate and fill AVFrame.extended_data and AVFrame.extended_buf. For planar formats, one buffer will be allocated for each plane.
Warning
: if frame already has been allocated, calling this function will leak memory. In addition, undefined behavior can occur in certain cases.
Parameters
frame frame in which to store the new buffers.
align Required buffer size alignment. If equal to 0, alignment will be chosen automatically for the current CPU. It is highly recommended to pass 0 here unless you know what you are doing.
Returns
0 on success, a negative AVERROR on error.
Examples:
encode_audio.c, encode_video.c, filter_audio.c, muxing.c, transcode_aac.c, and vaapi_encode.c.
Referenced by alloc_audio_frame(), alloc_picture(), get_input(), init_output_frame(), and main().
av_frame_is_writable()
int av_frame_is_writable (AVFrame * frame)
Check if the frame data is writable.
Returns
A positive value if the frame data is writable (which is true if and only if each of the underlying buffers has only one reference, namely the one stored in this frame). Return 0 otherwise.
If 1 is returned the answer is valid until av_buffer_ref() is called on any of the underlying AVBufferRefs (e.g. through av_frame_ref() or directly).
See also
av_frame_make_writable(), av_buffer_is_writable()
av_frame_make_writable()
int av_frame_make_writable (AVFrame * frame)
Ensure that the frame data is writable, avoiding data copy if possible.
Do nothing if the frame is writable, allocate new buffers and copy the data if it is not.
Returns
0 on success, a negative AVERROR on error.
See also
av_frame_is_writable(), av_buffer_is_writable(), av_buffer_make_writable()
Examples:
encode_audio.c, encode_video.c, and muxing.c.
Referenced by get_video_frame(), main(), and write_audio_frame().
av_frame_copy()
int av_frame_copy (AVFrame * dst, const AVFrame * src)
Copy the frame data from src to dst.
This function does not allocate anything, dst must be already initialized and allocated with the same parameters as src.
This function only copies the frame data (i.e. the contents of the data / extended data arrays), not any other properties.
Returns
>= 0 on success, a negative AVERROR on error.
av_frame_copy_props()
int av_frame_copy_props (AVFrame * dst, const AVFrame * src)
Copy only "metadata" fields from src to dst.
Metadata for the purpose of this function are those fields that do not affect the data layout in the buffers. E.g. pts, sample rate (for audio) or sample aspect ratio (for video), but not width/height or channel layout. Side data is also copied.
av_frame_get_plane_buffer()
AVBufferRef* av_frame_get_plane_buffer (AVFrame * frame, int plane)
Get the buffer reference a given data plane is stored in.
Parameters
plane index of the data plane of interest in frame->extended_data.
Returns
the buffer reference that contains the plane or NULL if the input frame is not valid.
av_frame_new_side_data()
AVFrameSideData* av_frame_new_side_data (AVFrame * frame, enum AVFrameSideDataType type, int size)
Add a new side data to a frame.
Parameters
frame a frame to which the side data should be added
type type of the added side data
size size of the side data
Returns
newly added side data on success, NULL on error
av_frame_get_side_data()
AVFrameSideData* av_frame_get_side_data (const AVFrame * frame, enum AVFrameSideDataType type)
Returns
a pointer to the side data of a given type on success, NULL if there is no side data with such type in this frame.
Referenced by decode_packet().
av_frame_remove_side_data()
void av_frame_remove_side_data (AVFrame * frame, enum AVFrameSideDataType type)
If side data of the supplied type exists in the frame, free it and remove it from the frame.
av_frame_apply_cropping()
int av_frame_apply_cropping (AVFrame * frame, int flags)
Crop the given video AVFrame according to its crop_left/crop_top/crop_right/ crop_bottom fields.
If cropping is successful, the function will adjust the data pointers and the width/height fields, and set the crop fields to 0.
In all cases, the cropping boundaries will be rounded to the inherent alignment of the pixel format. In some cases, such as for opaque hwaccel formats, the left/top cropping is ignored. The crop fields are set to 0 even if the cropping was rounded or ignored.
Parameters
frame the frame which should be cropped
flags Some combination of AV_FRAME_CROP_* flags, or 0.
Returns
>= 0 on success, a negative AVERROR on error. If the cropping fields were invalid, AVERROR(ERANGE) is returned, and nothing is changed.
av_frame_side_data_name()
const char* av_frame_side_data_name (enum AVFrameSideDataType type)
Returns
a string identifying the side data type