FFmpeg: doc/examples/muxing.c File Reference
muxing.c File Reference
libavformat API example.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <libavutil/avassert.h>
#include <libavutil/channel_layout.h>
#include <libavutil/opt.h>
#include <libavutil/mathematics.h>
#include <libavutil/timestamp.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>
#include <libswresample/swresample.h>
Data Structures
struct OutputStream
Macros
#define STREAM_DURATION 10.0
#define STREAM_FRAME_RATE 25 /* 25 images/s */
#define STREAM_PIX_FMT AV_PIX_FMT_YUV420P /* default pix_fmt */
#define SCALE_FLAGS SWS_BICUBIC
Functions
static void log_packet (const AVFormatContext *fmt_ctx, const AVPacket *pkt)
static int write_frame (AVFormatContext *fmt_ctx, const AVRational *time_base, AVStream *st, AVPacket *pkt)
static void add_stream (OutputStream *ost, AVFormatContext *oc, AVCodec **codec, enum AVCodecID codec_id)
static AVFrame * alloc_audio_frame (enum AVSampleFormat sample_fmt, uint64_t channel_layout, int sample_rate, int nb_samples)
static void open_audio (AVFormatContext *oc, AVCodec *codec, OutputStream *ost, AVDictionary *opt_arg)
static AVFrame * get_audio_frame (OutputStream *ost)
static int write_audio_frame (AVFormatContext *oc, OutputStream *ost)
static AVFrame * alloc_picture (enum AVPixelFormat pix_fmt, int width, int height)
static void open_video (AVFormatContext *oc, AVCodec *codec, OutputStream *ost, AVDictionary *opt_arg)
static void fill_yuv_image (AVFrame *pict, int frame_index, int width, int height)
static AVFrame * get_video_frame (OutputStream *ost)
static int write_video_frame (AVFormatContext *oc, OutputStream *ost)
static void close_stream (AVFormatContext *oc, OutputStream *ost)
int main (int argc, char **argv)
Detailed Description
libavformat API example.
Output a media file in any supported libavformat format. The default codecs are used.
Definition in file muxing.c.
Macro Definition Documentation
STREAM_DURATION
#define STREAM_DURATION 10.0
Examples:
muxing.c.
Definition at line 46 of file muxing.c.
Referenced by get_audio_frame(), and get_video_frame().
STREAM_FRAME_RATE
#define STREAM_FRAME_RATE 25 /* 25 images/s */
Examples:
muxing.c.
Definition at line 47 of file muxing.c.
Referenced by add_stream().
STREAM_PIX_FMT
#define STREAM_PIX_FMT AV_PIX_FMT_YUV420P /* default pix_fmt */
Examples:
muxing.c.
Definition at line 48 of file muxing.c.
Referenced by add_stream().
SCALE_FLAGS
#define SCALE_FLAGS SWS_BICUBIC
Examples:
muxing.c.
Definition at line 50 of file muxing.c.
Referenced by get_video_frame().
Function Documentation
log_packet()
static void log_packet (const AVFormatContext * fmt_ctx, const AVPacket * pkt) static
Examples:
muxing.c.
Definition at line 70 of file muxing.c.
Referenced by write_frame().
write_frame()
static int write_frame (AVFormatContext * fmt_ctx, const AVRational * time_base, AVStream * st, AVPacket * pkt) static
Examples:
muxing.c.
Definition at line 81 of file muxing.c.
Referenced by write_audio_frame(), and write_video_frame().
add_stream()
static void add_stream (OutputStream * ost, AVFormatContext * oc, AVCodec ** codec, enum AVCodecID codec_id) static
Examples:
muxing.c.
Definition at line 93 of file muxing.c.
Referenced by main().
alloc_audio_frame()
static AVFrame* alloc_audio_frame (enum AVSampleFormat sample_fmt, uint64_t channel_layout, int sample_rate, int nb_samples) static
Examples:
muxing.c.
Definition at line 187 of file muxing.c.
Referenced by open_audio().
open_audio()
static void open_audio (AVFormatContext * oc, AVCodec * codec, OutputStream * ost, AVDictionary * opt_arg) static
Examples:
muxing.c.
Definition at line 215 of file muxing.c.
Referenced by main().
get_audio_frame()
static AVFrame* get_audio_frame (OutputStream * ost) static
Examples:
muxing.c.
Definition at line 280 of file muxing.c.
Referenced by write_audio_frame().
write_audio_frame()
static int write_audio_frame (AVFormatContext * oc, OutputStream * ost) static
Examples:
muxing.c.
Definition at line 309 of file muxing.c.
Referenced by main().
alloc_picture()
static AVFrame* alloc_picture (enum AVPixelFormat pix_fmt, int width, int height) static
Examples:
muxing.c.
Definition at line 373 of file muxing.c.
Referenced by open_video().
open_video()
static void open_video (AVFormatContext * oc, AVCodec * codec, OutputStream * ost, AVDictionary * opt_arg) static
Examples:
muxing.c.
Definition at line 396 of file muxing.c.
Referenced by main().
fill_yuv_image()
static void fill_yuv_image (AVFrame * pict, int frame_index, int width, int height) static
Examples:
muxing.c.
Definition at line 440 of file muxing.c.
Referenced by get_video_frame().
get_video_frame()
static AVFrame* get_video_frame (OutputStream * ost) static
Examples:
muxing.c.
Definition at line 461 of file muxing.c.
Referenced by write_video_frame().
write_video_frame()
static int write_video_frame (AVFormatContext * oc, OutputStream * ost) static
Examples:
muxing.c.
Definition at line 507 of file muxing.c.
Referenced by main().
close_stream()
static void close_stream (AVFormatContext * oc, OutputStream * ost) static
Examples:
muxing.c.
Definition at line 542 of file muxing.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Examples:
muxing.c.
Definition at line 554 of file muxing.c.