FFmpeg: doc/examples/transcoding.c File Reference
transcoding.c File Reference
API example for demuxing, decoding, filtering, encoding and muxing.
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavfilter/buffersink.h>
#include <libavfilter/buffersrc.h>
#include <libavutil/opt.h>
#include <libavutil/pixdesc.h>
Data Structures
struct FilteringContext
struct StreamContext
Functions
static int open_input_file (const char *filename)
static int open_output_file (const char *filename)
static int init_filter (FilteringContext *fctx, AVCodecContext *dec_ctx, AVCodecContext *enc_ctx, const char *filter_spec)
static int init_filters (void)
static int encode_write_frame (AVFrame *filt_frame, unsigned int stream_index, int *got_frame)
static int filter_encode_write_frame (AVFrame *frame, unsigned int stream_index)
static int flush_encoder (unsigned int stream_index)
int main (int argc, char **argv)
Variables
static AVFormatContext * ifmt_ctx
static AVFormatContext * ofmt_ctx
static FilteringContext * filter_ctx
static StreamContext * stream_ctx
Detailed Description
API example for demuxing, decoding, filtering, encoding and muxing.
Definition in file transcoding.c.
Function Documentation
open_input_file()
static int open_input_file (const char * filename) static
Examples:
transcoding.c.
Definition at line 53 of file transcoding.c.
Referenced by main().
open_output_file()
static int open_output_file (const char * filename) static
Examples:
transcoding.c.
Definition at line 111 of file transcoding.c.
Referenced by main().
init_filter()
static int init_filter (FilteringContext * fctx, AVCodecContext * dec_ctx, AVCodecContext * enc_ctx, const char * filter_spec) static
Examples:
transcoding.c.
Definition at line 225 of file transcoding.c.
Referenced by init_filters().
init_filters()
static int init_filters (void) static
Examples:
transcoding.c.
Definition at line 374 of file transcoding.c.
Referenced by main().
encode_write_frame()
static int encode_write_frame (AVFrame * filt_frame, unsigned int stream_index, int * got_frame) static
Examples:
transcoding.c.
Definition at line 404 of file transcoding.c.
Referenced by filter_encode_write_frame(), and flush_encoder().
filter_encode_write_frame()
static int filter_encode_write_frame (AVFrame * frame, unsigned int stream_index) static
Examples:
transcoding.c.
Definition at line 440 of file transcoding.c.
Referenced by main().
flush_encoder()
static int flush_encoder (unsigned int stream_index) static
Examples:
transcoding.c.
Definition at line 484 of file transcoding.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Examples:
transcoding.c.
Definition at line 504 of file transcoding.c.
Variable Documentation
ifmt_ctx
AVFormatContext* ifmt_ctx static
Examples:
remuxing.c, and transcoding.c.
Definition at line 38 of file transcoding.c.
Referenced by main().
ofmt_ctx
AVFormatContext* ofmt_ctx static
Examples:
remuxing.c, and transcoding.c.
Definition at line 39 of file transcoding.c.
Referenced by main().
filter_ctx
FilteringContext* filter_ctx static
Examples:
transcoding.c.
Definition at line 45 of file transcoding.c.
stream_ctx
StreamContext* stream_ctx static
Examples:
transcoding.c.
Definition at line 51 of file transcoding.c.